# Generated by Django 5.0.4 on 2026-05-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Logo Header, Favicon, Banner Home', max_length=100)),
                ('image', models.ImageField(upload_to='assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
