# Generated by Django 5.0.4 on 2026-06-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluser_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('q1', '¿Cuál es el nombre de tu primera mascota?'), ('q2', '¿En qué ciudad naciste?'), ('q3', '¿Cuál es el nombre de tu madre?'), ('q4', '¿Cuál es tu color favorito?')], max_length=10, verbose_name='Pregunta')),
                ('answer', models.CharField(max_length=255, verbose_name='Respuesta (normalizada)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
