# Generated by Django 5.0.4 on 2026-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_securityquestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securityquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='question',
            field=models.CharField(choices=[('mascota', '¿Nombre de tu primera mascota?'), ('ciudad', '¿Ciudad donde naciste?'), ('madre', '¿Nombre de tu madre?')], max_length=50),
        ),
    ]
