# Generated by Django 5.0.4 on 2026-06-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_securityquestion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securityquestion',
            unique_together={('user', 'question')},
        ),
    ]
