# Generated by Django 5.0.4 on 2026-06-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_created_date_alter_cart_deleted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
