# Generated by Django 5.0.4 on 2026-05-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago'),
        ),
    ]
