# Generated by Django 5.0.4 on 2026-06-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_comprobante_pago'),
        ('products', '0004_historicalproduct_stock_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='comprobante_pago',
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=255, verbose_name='Dirección de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_confirmed',
            field=models.BooleanField(default=False, verbose_name='El usuario marcó que ya transfirió'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADO', 'Pago confirmado'), ('VIAJE', 'En camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
