# Generated by Django 5.0.4 on 2026-06-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_remove_order_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('ENVIO', 'Envío a domicilio'), ('RETIRO', 'Retiro en tienda')], default='ENVIO', max_length=20, verbose_name='Método de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección de entrega'),
        ),
    ]
