# Generated by Django 6.0.4 on 2026-05-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='category_product',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_product',
            new_name='product_category',
        ),
        migrations.RemoveField(
            model_name='historicalproductcategory',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='measure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de Medida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del producto'),
        ),
    ]
