# Generated by Django 5.0.4 on 2026-05-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_product_historicalproduct_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de venta'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de venta'),
        ),
    ]
