# Generated by Django 5.0.4 on 2026-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_historicalproduct_stock_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicador',
            name='created_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalindicador',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicador',
            name='modified_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalindicador',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='created_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='modified_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='created_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='modified_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='created_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='modified_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
